<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI6P5tNI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI6P5tNI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerI6P5tNI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerI6P5tNI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerI6P5tNI\appAppKernelProdContainer([
    'container.build_hash' => 'I6P5tNI',
    'container.build_id' => 'd3e2a723',
    'container.build_time' => 1710144270,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI6P5tNI');
