<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3dom0Cr\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3dom0Cr/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3dom0Cr.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3dom0Cr\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3dom0Cr\appAppKernelProdContainer([
    'container.build_hash' => '3dom0Cr',
    'container.build_id' => 'e405fcce',
    'container.build_time' => 1710151360,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3dom0Cr');
