<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcbxKda\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcbxKda/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAcbxKda.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAcbxKda\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAcbxKda\appAppKernelProdContainer([
    'container.build_hash' => 'AcbxKda',
    'container.build_id' => '81d52124',
    'container.build_time' => 1710149930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcbxKda');
