version: '3'
services:
  web:
    build: apache
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./apache/julio.lan.conf:/etc/apache2/sites-enabled/julio.lan.conf
      - ./apache/certificados:/certificados
    ports:
      - 80:80
      - 443:443
  bd:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./bd/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - datos:/var/lib/mysql
      - ./bd:/bd
volumes:
  datos:
