<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4ch2bT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4ch2bT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerC4ch2bT.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerC4ch2bT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerC4ch2bT\appAppKernelProdContainer([
    'container.build_hash' => 'C4ch2bT',
    'container.build_id' => '59be3c00',
    'container.build_time' => 1710145561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4ch2bT');
